### ISSUE TITLE
Is any difference between to_dict(only=()) and serialize_only?

### ISSUE THREAD

**Issue by gotounix** [n0nSmoker/SQLAlchemy-serializer#18]
I read the ``README``, it have two lines:
``serialize_only and serialize_rules work the same way as to_dict's arguments``
``If you pass rules in serialize_only the serializer becomes NOT greedy and returns ONLY fields listed there.``

While I test ``to_dict(only=())`` and ``serialize_only`` in my codes:
```
class Flow(SerializerMixin, Model):
    __tablename__ = 'flows'

    id = Column(db.Integer, primary_key=True)
    serialize_only = ('name', 'nodes.name', 'nodes.category', 'nodes.mode', 'nodes.sub_flow')

    name = Column(db.String(100), nullable=False)

    nodes = relationship('Node',
                         backref=db.backref('flow', uselist=False),
                         single_parent=True,
                         cascade='all, delete, delete-orphan',
                         order_by='asc(Node.seq)')


class Node(SerializerMixin, Model):
    __tablename__ = 'nodes'

    id = Column(db.Integer, primary_key=True)
    flow_id = reference_col('flows', nullable=False)

    name = Column(db.String(100), nullable=False)
    category = Column(db.String(100), default=0)
    mode = Column(db.Integer(), default=0)

    @property
    def sub_flow(self):
        if self.category == 'sub_flow':
            flow = Flow.query.filter_by(id=self.mode).first()
            return flow
        else:
            return None
```

I found, if I use ``flow.to_dict(only=('name', 'nodes.name', 'nodes.category', 'nodes.mode', 'nodes.sub_flow'))``, it will ``Max recursion``. And set ``serialize_only = ('name', 'nodes.name', 'nodes.category', 'nodes.mode', 'nodes.sub_flow')`` in ``Flow``, everything works fine.

Is ``serialize_only`` works for all instances and ``only`` just work for the instance that called ``to_dict``?

And I found ``serialize_only`` will override ``only`` in ``to_dict``, so I can't serialize another data structure.

Is there a way to set a param for making ``only`` for all instances which is same model class?

**Comment by n0nSmoker** [comment]
The brief answer to your question
_Is there a way to set a param for making only for all instances which is same model class?_
Will be no =)
The point here is that `only` is just rules for the whole tree, but not for some kind of model in it.
 
Rules that you want to apply to certain kind of model should be placed in `serialize_only ` in that model.

But anyways its an interesting case, I think there should be another type of rules for it.
If you've implemented it I would be pleased to get a pull request =))
