### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by wbhst83** [n0nSmoker/SQLAlchemy-serializer#20]
So I had to force a logging change for two reasons, the print statements slow things down and secondly fills up my logs with a crap load of actions. While maybe helpful in debug situations, not ideal in production. Maybe I missed in documentation, but can we change the default log level to WARN, unless defined otherwise? I did the following in my models file for my Flask app and solved for me.

`serializer_logger = logging.getLogger('serializer')`
`serializer_logger.setLevel(level="WARN")`

**Comment by n0nSmoker** [comment]
Done 
https://pypi.org/project/SQLAlchemy-serializer/1.3.4.3/
