### ISSUE TITLE
Change Default Datetime Format

### ISSUE THREAD

**Issue by BenMcLean981** [n0nSmoker/SQLAlchemy-serializer#21]
I think the default the default datetime format should change. I have a situation where a lot of my tables are storing datetime to the second, but the serializer rounds them to the nearest minute.

this fixes it, but I think that this should be the default as it's probably more common to have data stored to the second than not.
datetime_format = '%Y-%m-%d %H:%M:%S'

**Comment by BrendanSimon** [comment]
I would have thought `isoformat` would be the most portable and cover all situations.

**Comment by BenMcLean981** [comment]
Is ISO-8601 not 2020-09-03T18:13:49+00:00 or 2020-09-03T18:13:49Z for UTC?

![Code_WsTZ2MvDaK](https://user-images.githubusercontent.com/35312653/92153025-a20ec680-edf1-11ea-8865-314ba0a13298.png)

**Comment by n0nSmoker** [comment]
You can define default formats for all models the. following way
```python
from sqlalchemy_serializer import SerializerMixin

class CustomSerializerMixin(SerializerMixin):
    date_format = '%s'  # Unixtimestamp (seconds)
    datetime_format = '%Y %b %d %H:%M:%S.%f'
    time_format = '%H:%M.%f'
    decimal_format = '{:0>10.3}'
```

**Comment by n0nSmoker** [comment]
I've changed the default datetime format
I think we should keep seconds
So no it is
`datetime_format = '%Y-%m-%d %H:%M:%S'`
