### ISSUE TITLE
how to deserialize back to model object

### ISSUE THREAD

**Issue by BrendanSimon** [n0nSmoker/SQLAlchemy-serializer#22]
Is there a way to deserialise from dict back to model object?  a `from_dict()` perhaps?

I serialze to dict, and the to JSON via `dumps()`.  Works a treat.

Now I want to do the reverse.  JSON => dict => Model.

I tried using the model constructor with a unpacked dict.  exampe:

```python
d = json.loads( json_input )
log = Log( **d )
```

However one of the fields is `DateTime` and I get the following error.

```
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO "Log" (timestamp, temperature) VALUES (?, ?)]
[parameters: [{'timestamp': '2020-08-06 13:11', 'temperature': 23.4}]]
``

**Comment by PlaNOid** [comment]
Hi, you must explicitly convert the string to DateTime object before you passing it to the constructor. 
Because after converting a JSON to a dictionary,  you got a 'timestamp' like string, not a DateTime object.

**Comment by BrendanSimon** [comment]
ok.  Thanks.

I'm used to working with the `attrs` module to define classes.  It adds a lot of boiler plate and helper functions like `asdict()` and `astuple()`.

`attrs` doesn't have the reverse, but there is another module called `cattrs`, which has `structure()` and `unstructure()`, where `structure()` converts from dict to class, and `unstructure()` converts from class to dict.  Apart from being generic, it also has built in support for `attrs`, so that `attrs` decorated classes are automatically converted without having to define custom hooks.

I might even be able to use `attrs` or `cattrs` somehow here?

**Comment by n0nSmoker** [comment]
If I correctly got your question, here is a handy function for populating models
```python
def setattrs(obj, ignore_nulls=False, **kwargs):
    """ Setting multiple object attributes at once """

    attrs = (a for a in dir(obj) if not a.startswith("_"))
    for attr in attrs:
        if attr in kwargs and (
            kwargs[attr] is not None and ignore_nulls or not ignore_nulls
        ):
            setattr(obj, attr, kwargs[attr])
```
But all fields should be already converted to the right format
