### ISSUE TITLE
Rules extension doesn't work with relationships

### ISSUE THREAD

**Issue by martarho** [n0nSmoker/SQLAlchemy-serializer#26]
I'm trying to use the sqlalchemy-serializer to transform my query outputs to json. My models link to each other with relationships. To make sure I can export the tables on their own (without the link to children tables) I added some negative serialize rules in the models. However, when I try to overwrite them at the query level, I encountered the following error:

```
test.py 72 <module>
pp.pprint(i.to_dict(rules=("areas")))

serializer.py 92 to_dict
return s(self, only=only, extend=rules)

serializer.py 117 __call__
return self.serialize(value)

serializer.py 168 serialize
return callback(value)

serializer.py 265 serialize_model
v = getattr(value, k)

AttributeError:
'Object' object has no attribute 's'
```
You can find the test.py code attached to reproduce this issue 

[test.txt](https://github.com/n0nSmoker/SQLAlchemy-serializer/files/5754325/test.txt)

**Comment by elliott-king** [comment]
It looks like you didn't [add a comma](https://github.com/n0nSmoker/SQLAlchemy-serializer#one-element-tuples) at the end of `pp.pprint(i.to_dict(rules=("areas")))`

**Comment by n0nSmoker** [comment]
Yea, thats right, https://github.com/n0nSmoker/SQLAlchemy-serializer#one-element-tuples
I've just tested your case, added comma (`("areas") --> ("areas",)`) and got this output
```
{'name': 'Dorm', 'id': 1}

{'name': 'Chair', 'area_id': 1, 'id': 1}
{'name': 'Table', 'area_id': 1, 'id': 2}

{'area_id': 1, 'id': 1, 'areas': {'name': 'Dorm', 'id': 1}, 'name': 'Chair'}
{'area_id': 1, 'id': 2, 'areas': {'name': 'Dorm', 'id': 1}, 'name': 'Table'}
```
And I suggest to use the latest version of serializer 
https://pypi.org/project/SQLAlchemy-serializer/1.4
