### ISSUE TITLE
Auto-detect list queries

### ISSUE THREAD

**Issue by sarojbelbase** [n0nSmoker/SQLAlchemy-serializer#34]
If I use `SerializerMixin` inside my model
```
class Category(Model, SerializerMixin):
    __tablename__ = 'category'

    category_id = Column(Integer(), primary_key=True)
    category_name = Column(String(100))
```
It doesn't have support for list type, It works on the single item `Category.query.first()` but not on queries with list type, I need to use list comprehension for list type like in the example below:

```python
        categories = Category.query.all()
        response = [category.to_dict() for category in categories]
```

DESIRED SOLUTION:

```python
        categories = Category.query.all()
        response = categories.to_dict()
```

**Comment by n0nSmoker** [comment]
`Category.query.all()` returns a `list`
So you want a custom list class. Your solution should look like
```python
        categories = CustomList(Category.query.all())
        response = categories.to_dict()
```
Because we do not control the source of that list
On the next iteration we have
```python
        response = custom_list_with_to_dict_interface(Category.query.all())
```
So basically you need a helper which wraps `[category.to_dict() for category in categories]` like the following
```python
def custom_list_with_to_dict_interface(iterable, *args, **kwargs):
    return [category.to_dict(*args, **kwargs) for category in iterable]
```

**Comment by n0nSmoker** [comment]
I've added the helper Since there were so many votes
Here is the [description](https://github.com/n0nSmoker/SQLAlchemy-serializer?tab=readme-ov-file#serialize_collection) how to use
