### ISSUE TITLE
thank author contribution to this library

### ISSUE THREAD

**Issue by Toudaozhe** [n0nSmoker/SQLAlchemy-serializer#4]
我来自中国江苏无锡，最近在模仿php的laravel写一份flask版的api，作者这个库帮助了我，但是orm的all()方法查询的结果是list，to_dict是无法处理的，希望作者能完善下，我自己在基类里也做了相应的修改，在此表示感谢！thank author~

**Comment by n0nSmoker** [comment]
Can you show the code?
