### ISSUE TITLE
Multiple results error

### ISSUE THREAD

**Issue by stefanlex90** [n0nSmoker/SQLAlchemy-serializer#5]
Hello, first of all thank you for this serializer .
I have issue when i try to serialize Model.query.all() when i have multiple results.

Example code:
`
contacts = Contact.query.all()
return contacts.to_dict()
`
I got error: AttributeError: 'list' object has no attribute 'to_dict'

**Comment by laith43d** [comment]
The same here.

**Comment by n0nSmoker** [comment]
Thank you, but it is not a bug.
Contact.query.all() - returns a list object (list of models) and it is obvious that it has no to_dict method. You should call to_dict method on every model's instance
To serialize it you should do smth like this:
```
contacts = Contact.query.all()
return [c.to_dict() for c in contacts]
```
