### ISSUE TITLE
readme needs changing

### ISSUE THREAD

**Issue by oziee** [n0nSmoker/SQLAlchemy-serializer#8]
Hi

I have been playing with this neat addin all day.. its great
I did pull my hair out for an hour trying to debug with rules were not working
turns out using your code samples in the readme do not work if you only pass in 1 rule.. if you pass in more than 1 then it works

from the readme.. this works
```
result = item.to_dict(rules=('-somefield', '-anotherone.nested1.nested2'))
```

this does not
```
result = item.to_dict(rules=('-somefield'))
```

seems RULES is setting a Set() 
so the correct way to pass in rules etc would be `using curly brackets`
```
result = item.to_dict(rules={'-somefield', '-anotherone.nested1.nested2'})
```
using `curly brackets` passing in just one {'some field'} does not cause errors

just FYI for anyone looking

**Comment by n0nSmoker** [comment]
Thank you for feedback! You're a bit wrong
you missed the comma in this line
```
result = item.to_dict(rules=('-somefield'))
```
('somestring') - is just a string and ('somestring',) is a tuple

So your line should look like
```
result = item.to_dict(rules=('-somefield',))
```
And as rules you can pass any iterable
You can check out the [Schema](https://github.com/n0nSmoker/SQLAlchemy-serializer/blob/master/sqlalchemy_serializer/lib/rules.py#L21) class  to understand how serialiser treats rules

**Comment by oziee** [comment]
ahh did not even think of that :) funny that passing in a {}set worked too :)
